### ISSUE TITLE
使用realm在debug js remotely模式下出现错误。

### ISSUE THREAD

**Issue by zhuanglong** [mochixuan/Mung#1]
index.ios.bundle:7769DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8083/create_session'.

index.ios.bundle:7761Realm failed to connect to the embedded debug server inside the app. If attempting to use Chrome debugging from a device, ensure the device is reachable on the same network as this machine.

**Comment by mochixuan** [comment]
这个没遇到过，我是在windows下开发的，Mac下微调，是可以运行的。

**Comment by stlemon** [comment]
这问题在realm-js的issues也好多人提，我找了一圈，试了好几个方法也都没用。只能在非debug环境下用。

**Comment by mochixuan** [comment]
realm的版本问题，我开发时也遇到了，我现在版本是"realm": "2.2.14"可以用

**Comment by stlemon** [comment]
@mochixuan 我升级到了最新版本 2.4.1，还是有这个错误。难道说新版本才有的这歌问题吗？不行我降降版本试试。

**Comment by mochixuan** [comment]
嗯，反正之前是这个问题我在realm.js上看到的

**Comment by stlemon** [comment]
好的，谢谢
