### ISSUE TITLE
为什么运行后提示网络请求错误呢

### ISSUE THREAD

**Issue by markdashi** [mochixuan/Mung#2]
为什么运行后提示网络请求错误呢

**Comment by mochixuan** [comment]
1.你是Mac下还是Windows下，
2.你是Deebug模式下还是打包后，
3.能不能粘贴下log，我看下问题
              --谢谢

**Comment by mochixuan** [comment]
1.你是Mac下还是Windows下，
2.你是Debug模式下还是打包后，
3.是那个页面出现这个情况，
--谢谢

**Comment by markdashi** [comment]
谢谢你的回答，Mac debug 下，我看baseURL 怎么是http://ip:2000

**Comment by mochixuan** [comment]
你好，我刚才测试了以下没有问题，可能你开启了远程调试吧，开了这个可能会有些未知的问题，windows下也出现过，但正常打包后是没有问题。对于你的问题“是有本地开启服务器吗”，这个我没有开。项目没有多余的代码和后台。
