### ISSUE TITLE
app:compileDebugJavaWithJavac - is not incremental

### ISSUE THREAD

**Issue by verglas** [mochixuan/Mung#3]
报错，GOOGLE找遍，不知道什么问题。

react-native run-android 93%时报错，如下：
`
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
D:\xampp1\htdocs\NewProject\android\app\src\main\java\com\newproject\MainApplication.java:19: : Ҳ
      return BuildConfig.DEBUG;
             ^
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
`

尝试解决：

1，`
cd android && gradlew clean
cd .. && react-native run-android`

2，JAVA_HOME 重装 修改

3，`repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://dl.bintray.com/underdark/android/'
        }
    }`

都没解决。。。

**Comment by verglas** [comment]
> {
	"name": "MomentWeather",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"babel-preset-react-native-stage-0": "^1.0.1",
		"mobx": "^3.3.2",
		"mobx-react": "^4.3.5",
		"pinyin": "^2.8.3",
		"react": "^16.0.0",
		"react-native": "^0.50.4",
		"react-native-baidu-map": "^0.6.0",
		"react-navigation": "^1.0.0-beta.21"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-plugin-transform-decorators-legacy": "^1.3.4",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0"
	},
	"jest": {
		"preset": "react-native"
	}
}

**Comment by mochixuan** [comment]
你可以看看你的错误，是无法连接设备的问题。： Make sure you have an Android emulator running or a device connected and have set up your Android development environment
