### ISSUE TITLE
换肤功能实现方式

### ISSUE THREAD

**Issue by lizhuoyuan** [mochixuan/Mung#5]
您好, 这里下载了您的项目
看了下源码 , 没有看懂怎么实现的换肤功能
可否解释下?
我用的ReactNavigation写换肤功能未果,想学一下

**Comment by mochixuan** [comment]
现在公司项目换肤是redux及其好用和及其合理，这个项目用的是Movie.js里面。
onChangeTheme() {
        this.setState({
            MainColor:queryThemeColor(), //技巧
        })
    }
